[workspace]
resolver = "2"

members = [
  "liquid-staking",
  "liquid-staking/meta",
  "liquid-staking/interactor",
  "vote-sc",
  "vote-sc/meta",
  "delegation/interactor",
  #"governance/interactor",
]
