contract_address = "erd1qqqqqqqqqqqqqpgqak8zt22wl2ph4tswtyc39namqx6ysa2sd8ss4xmlj3"
delegation_address = "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqhllllsajxzat"
vote_address = "erd1qqqqqqqqqqqqqpgqved56l3s3mglk9msryuttld8m8xls540d8ssz3xeaz"
