// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           30
// Async Callback:                       1
// Total number of exported functions:  32

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        addLiquidity
        removeLiquidity
        unbondTokens
        withdrawAll
        claimRewards
        recomputeTokenReserve
        delegateRewards
        getLsValueForPosition
        registerLsToken
        registerUnstakeToken
        getState
        getLsTokenId
        getLsSupply
        getVirtualEgldReserve
        getRewardsReserve
        getTotalWithdrawnEgld
        getUnstakeTokenId
        whitelistDelegationContract
        changeDelegationContractAdmin
        changeDelegationContractParams
        getDelegationStatus
        getDelegationContractStakedAmount
        getDelegationContractUnstakedAmount
        getDelegationContractUnbondedAmount
        setStateActive
        setStateInactive
        getDelegationAddressesList
        getAddressesToClaim
        getDelegationClaimStatus
        getDelegationContractData
        callBack
    )
}
