// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback:                       1
// Total number of exported functions:  31

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquid_staking
    (
        addLiquidity
        removeLiquidity
        unbondTokens
        claimRewards
        recomputeTokenReserve
        delegateRewards
        getLsValueForPosition
        registerLsToken
        registerUnstakeToken
        setStateActive
        setStateInactive
        getState
        getLsTokenId
        getLsSupply
        getVirtualEgldReserve
        getRewardsReserve
        getTotalWithdrawnEgld
        getUnstakeTokenId
        getUnstakeTokenSupply
        whitelistDelegationContract
        changeDelegationContractAdmin
        changeDelegationContractParams
        getDelegationStatus
        getDelegationContractStakedAmount
        getDelegationContractUnstakedAmount
        getDelegationContractUnbondedAmount
        getDelegationAddressesList
        getDelegationClaimStatus
        getDelegationContractData
        callBack
    )
}
