// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback:                       1
// Total number of exported functions:  31

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    liquid_staking
    (
        addLiquidity
        removeLiquidity
        unbondTokens
        claimRewards
        recomputeTokenReserve
        delegateRewards
        getLsValueForPosition
        registerLsToken
        registerUnstakeToken
        setStateActive
        setStateInactive
        getState
        getLsTokenId
        getLsSupply
        getVirtualEgldReserve
        getRewardsReserve
        getTotalWithdrawnEgld
        getUnstakeTokenId
        getUnstakeTokenSupply
        whitelistDelegationContract
        changeDelegationContractAdmin
        changeDelegationContractParams
        getDelegationStatus
        getDelegationContractStakedAmount
        getDelegationContractUnstakedAmount
        getDelegationContractUnbondedAmount
        getDelegationAddressesList
        getDelegationClaimStatus
        getDelegationContractData
        callBack
    )
}
