// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    vote_sc
    (
        init => init
        upgrade => upgrade
        set_root_hash => set_root_hash
        set_liquid_staking_address => set_liquid_staking_address
        delegate_vote => delegate_vote
        delegate_test_vote => delegate_test_vote
        liquid_staking_sc => liquid_staking_sc
        getProposalRootHash => get_root_hash
        confirmVotingPower => confirm_voting_power
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
