// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    vote_sc
    (
        init => init
        set_root_hash => set_root_hash
        set_liquid_staking_address => set_liquid_staking_address
        delegate_vote => delegate_vote
        getProposalRootHash => get_root_hash
        confirmVotingPower => confirm_voting_power
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
