[package]
name = "vote-sc"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs.git"
rev = "2cf3e0b8fe53654e63924bc524a5db518f7cb469"
